shopee-tedu/Controllers/CartController.cs
using Model.Dao;
using Model.EF;
using shopee_tedu.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace shopee_tedu.Controllers
{
    public class CartController : Controller
    {
        private const string CartSession = "CartSession";
        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }

        public JsonResult DeleteAll()
        {
            Session[CartSession] = null;
            return Json(new
            {
                status = true
            });
        }

        public JsonResult Delete(long id)
        {
            var sessionCart = (List<CartItem>)Session[CartSession];
            sessionCart.RemoveAll(x => x.Product.ID == id);
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        public JsonResult Update(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart = (List<CartItem>)Session[CartSession];

            foreach (var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(x => x.Product.ID == item.Product.ID);
                if (jsonItem != null)
                {
                    item.Quantity = jsonItem.Quantity;
                }
            }
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        public ActionResult AddItem(long productId, int quantity)
        {
            var product = new ProductDao().ViewDetail(productId);
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.Product.ID == productId))
                {

                    foreach (var item in list)
                    {
                        if (item.Product.ID == productId)
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    //tạo mới đối tượng cart item
                    var item = new CartItem();
                    item.Product = product;
                    item.Quantity = quantity;
                    list.Add(item);
                }
                //Gán vào session
                Session[CartSession] = list;
            }
            else
            {
                //tạo mới đối tượng cart item
                var item = new CartItem();
                item.Product = product;
                item.Quantity = quantity;
                var list = new List<CartItem>();
                list.Add(item);
                //Gán vào session
                Session[CartSession] = list;
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Payment()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }

        [HttpPost]
        public ActionResult Payment(string shipName, string mobile, string address, string email)
        {
            var order = new Order();
            order.CreatedDate = DateTime.Now;
            order.ShipAddress = address;
            order.ShipMobile = mobile;
            order.ShipName = shipName;
            order.ShipEmail = email;

            try
            {
                var id = new OrderDao().Insert(order);
                var cart = (List<CartItem>)Session[CartSession];
                var detailDao = new Model.Dao.OrderDetailDao();
                decimal total = 0;
                foreach (var item in cart)
                {
                    var orderDetail = new OrderDetail();
                    orderDetail.ProductID = item.Product.ID;
                    orderDetail.OrderID = id;
                    orderDetail.Price = item.Product.Price;
                    orderDetail.Quantity = item.Quantity;
                    detailDao.Insert(orderDetail);

                    total += (item.Product.Price.GetValueOrDefault(0) * item.Quantity);
                }
                string content = System.IO.File.ReadAllText(Server.MapPath("~/assets/client/template/neworder.html"));

                content = content.Replace("{{CustomerName}}", shipName);
                content = content.Replace("{{Phone}}", mobile);
                content = content.Replace("{{Email}}", email);
                content = content.Replace("{{Address}}", address);
                content = content.Replace("{{Total}}", total.ToString("N0"));
                var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

                //new MailHelper().SendMail(email, "Đơn hàng mới từ OnlineShop", content);
                //new MailHelper().SendMail(toEmail, "Đơn hàng mới từ OnlineShop", content);
            }
            catch (Exception ex)
            {
                //ghi log
                return Redirect("/loi-thanh-toan");
            }
            return Redirect("/hoan-thanh");
        }

        public ActionResult Success()
        {
            return View();
        }
    }
}

shopee-tedu/Views/Cart/Index.cshtml
@model List<shopee_tedu.Models.CartItem>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section jsFooter{

    <script src="/assets/client/js/controller/cartController.js"></script>
}
<div class="content">
    <div class="section group">
        @if (Model.Count > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <td>Mã SP</td>
                        <td>Tên SP</td>
                        <td>Ảnh SP</td>
                        <td>Số lượng</td>
                        <td>Đơn giá</td>
                        <td>Thành tiền</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Product.ID</td>
                            <td>@item.Product.Name</td>
                            <td><img src="@item.Product.Image" width="100" /></td>
                            <td><input type="text" class="txtQuantity" data-id="@item.Product.ID" value="@item.Quantity" /></td>
                            <td>@item.Product.Price.GetValueOrDefault(0).ToString("N0")</td>
                            <td>@((item.Product.Price.GetValueOrDefault(0) * item.Quantity).ToString("N0"))</td>
                            <td><a href="#" data-id="@item.Product.ID" class="btn-delete">Xoá</a></td>
                        </tr>
                    }

                </tbody>
            </table>

            <button id="btnContinue" class="btn">Tiếp tục mua hàng</button>
            <button id="btnUpdate" class="btn">Cập nhật giỏ hàng</button>
            <button id="btnDeleteAll" class="btn">Xoá giỏ hàng</button>
            <button id="btnPayment" class="btn">Thanh toán</button>
        }
        else
        {
            <span class="alert alert-danger">Chưa có sản phẩm nào trong giỏ hàng</span>
        }

    </div>
</div>

shopee-tedu/Views/Cart/Payment.cshtml
@model List<shopee_tedu.Models.CartItem>
@{
    ViewBag.Title = "Thanh toán";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content">
    <div class="section group">
        @if (Model.Count > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <td>Mã SP</td>
                        <td>Tên SP</td>
                        <td>Ảnh SP</td>
                        <td>Số lượng</td>
                        <td>Đơn giá</td>
                        <td>Thành tiền</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Product.ID</td>
                            <td>@item.Product.Name</td>
                            <td><img src="@item.Product.Image" width="100" /></td>
                            <td><input type="text" class="txtQuantity" data-id="@item.Product.ID" value="@item.Quantity" /></td>
                            <td>@item.Product.Price.GetValueOrDefault(0).ToString("N0")</td>
                            <td>@((item.Product.Price.GetValueOrDefault(0) * item.Quantity).ToString("N0"))</td>
                            <td><a href="#" data-id="@item.Product.ID" class="btn-delete">Xoá</a></td>
                        </tr>
                    }

                </tbody>
            </table>
        }

    </div>
    <div class="section group">
        <div class="col-md-6">
            @using (Html.BeginForm("Payment", "Cart", FormMethod.Post))
            {
                <div class="form-group">
                    <label>Người nhận</label>
                    <input name="shipName" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Điện thoại</label>
                    <input name="mobile" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Địa chỉ</label>
                    <input name="address" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input name="email" class="form-control" />
                </div>
                <button type="submit" class="btn">Gửi đơn hàng</button>
            }
        </div>

    </div>
</div>

shopee-tedu/Views/Cart/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="alert alert-success">
    Bạn vừa mua hàng thành công.
</div>